apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedback-microservice
  labels:
    app: team1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: team1
  template:
    metadata:
      labels:
        app: team1
    spec:
      containers:
      - name: feedback-container
        image: ${IMAGE_NAME}
        ports:
        - containerPort: 80
